#!/usr/bin/env bash
# This script is simply a wrapper around ejslint that returns a non-zero exit
# status on one or more lint errors (currently ejslint always returns an exit
# status of 0). If and when https://github.com/RyanZim/EJS-Lint does the same,
# this script will no longer be needed.
EJSLINT_ARGS=${@:-macros/**/*.ejs}
OUT=$(/node_modules/.bin/ejslint $EJSLINT_ARGS)
if [[ $OUT ]]; then
    printf "$OUT\n"
    exit 1
else
    exit 0
fi
